name: example
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.0.0
environment:
  sdk: ^3.7.0
dependencies:
  artifact: ^1.0.16
  fire_api: ^1.5.1
  fire_crud: 
    path: ../
dev_dependencies:
  artifact_gen: ^1.1.0
  build_runner: ^2.10.0
  lints: ^5.0.0
  test: ^1.24.0
  fire_crud_gen:
    path: ../fire_crud_gen
scripts: 
  build: flutter pub run build_runner build --delete-conflicting-outputs