name: example
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.0.0
environment:
  sdk: ^3.7.0
dependencies:
  artifact: ^1.0.5
  dart_mappable: ^4.5.0
  fire_api: ^1.3.0
  fire_crud: 
    path: ../
dev_dependencies:
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.5.0
  lints: ^5.0.0
  test: ^1.24.0
scripts: 
  build: flutter pub run build_runner build --delete-conflicting-outputs