builders:
  fire_crud:
    import: "package:fire_crud_gen/crud_builder.dart"
    builder_factories: ["modelCrudBuilder"]
    build_extensions: { r"$lib$": ["gen/crud.gen.dart"] }
    auto_apply: dependents
    build_to: source