builders:
  model_crud_builder:
    import: "package:fire_crud/gen/crud_builder.dart"
    builder_factories: ["modelCrudPerFileBuilder"]
    build_extensions: { ".dart": [".crud.dart"] }
    auto_apply: dependents
    build_to: source