name: fire_crud
description: CRUD Operations for firestore
version: 3.1.3
homepage: https://github.com/ArcaneArts/fire_crud
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  pylon_codec: '>=1.0.0 <2.0.0'
  collection_walker: '>=2.0.0 <3.0.0'
  toxic: '>=1.3.0 <1.4.0'
  fire_api: '>=1.3.0 <2.0.0'
  throttled: '>=1.0.1 <2.0.0'
  rxdart: '>=0.27.7 <0.29.0'
  synchronized: '>=3.1.0 <4.0.0'
  build: ">=2.4.0"
  source_gen: ">=2.0.0"
  analyzer: ">=6.4.1 <8.0.0"
  glob: ">=2.1.0 <3.0.0"
  artifact: ">=1.0.5 <2.0.0"
dev_dependencies:
  build_runner: ^2.4.15 
  code_builder: ^4.10.0  