name: fire_crud
description: CRUD Operations for firestore
version: 2.3.5
homepage: https://github.com/ArcaneArts/fire_crud
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  collection_walker: '>=2.0.0 <3.0.0'
  toxic: '>=1.3.0 <1.4.0'
  fire_api: '>=1.1.7 <1.2.0'
  throttled: '>=1.0.1 <2.0.0'
  rxdart: '>=0.27.7 <0.29.0'
  synchronized: '>=3.1.0 <4.0.0'
