name: fire_crud_gen
description: Generator for fire crud
version: 1.1.2
homepage: https://github.com/ArcaneArts/fire_crud
environment:
  sdk: ^3.7.0
dependencies:
  build: ">=4.0.0 <5.0.0"
  source_gen: ">=4.0.0 <5.0.0"
  analyzer: ">=8.0.0 <9.0.0"
  glob: ">=2.1.0 <3.0.0"
  artifact: ">=1.0.16 <2.0.0"
  toxic: ">=1.3.0 <2.0.0"
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
